# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipuser',
            name='fav_artist',
            field=models.ManyToManyField(to='general.Artist'),
        ),
    ]
